const mongo = new Mongo()
const db = mongo.getDB('test')
let collections = db.getCollectionNames()
print('删除之前的集合:')
printjson(collections)
let coll = db.getCollection('newCollection')
coll.drop()
collections = db.getCollectionNames()
print('删除之后的集合:')
printjson(collections)